name: 'Telegram_Action'
description: 'Telegram action that can run on MacOS runners'
inputs:
  TELEGRAM_TOKEN:  # id of input
    description: 'telegram token'
    required: true
    default: 'World'
  TELEGRAM_TO:  # id of input
    description: 'telegram to id'
    required: true
    default: 'World'
  message:  # id of input
    description: 'message'
    required: true
    default: 'World'
  file:  # id of input
    description: 'file path'
    required: false
    default: ""
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
